services:
  mongo:
    image: mongo:7
    container_name: petfly-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: petfly-backend
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI={MONGO_URI}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongo

volumes:
  mongo-data:
